function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("@render:", "use_camera_projection")
	msg.post("camera", "acquire_camera_focus")

	-- Rotate the cube to make the starter scene visibly alive.
	go.animate(".", "euler.y", go.PLAYBACK_LOOP_FORWARD, 360, go.EASING_INOUTQUAD, 6)

	-- Give the two spheres different colors.
	go.set("/spheres#right", "tint", vmath.vector4(0, 0.5, 1, 1))
	go.set("/spheres#left", "tint", vmath.vector4(1, 0.5, 0, 1))

	-- Initial directional light position.
	self.light = vmath.vector4(0, go.get_position().y + 2, go.get_position().z + 2, 0)
end

function on_input(self, action_id, action)
	-- Move the directional light with mouse or touch input.
	self.light.x = 3 * ((action.x - 960) / 960)
	self.light.z = -3 * ((action.y - 540) / 540)

	go.set("#cube", "light", self.light)
	go.set("/plane#quad", "light", self.light)
	go.set("/spheres#right", "light", self.light)
	go.set("/spheres#left", "light", self.light)
end
